# Generated by Django 2.2.3 on 2019-08-24 14:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20190822_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aq_title', models.CharField(max_length=400)),
                ('aq_slug', models.CharField(max_length=500)),
                ('aq_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('aq_created', models.DateField(auto_now_add=True)),
                ('aq_updated', models.DateField(auto_now_add=True)),
                ('aq_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('aq_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_ques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
