# Generated by Django 2.2.3 on 2019-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_askquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='aq_updated',
            new_name='updated',
        ),
    ]
