# Generated by Django 2.2.3 on 2019-08-31 14:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190827_1719'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='askquestion',
            managers=[
                ('ask_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='askquestion',
            old_name='slug',
            new_name='AQslug',
        ),
    ]
