# Generated by Django 2.2.3 on 2019-08-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190831_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askquestion',
            old_name='AQslug',
            new_name='slug',
        ),
    ]
