# Generated by Django 2.2.3 on 2019-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190831_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='default_post_img.jpg', upload_to='post_images'),
        ),
    ]
