# Generated by Django 2.2.3 on 2019-09-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190903_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostBanner',
        ),
    ]
