# Generated by Django 2.2.3 on 2019-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190904_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(default='default_post_img.jpg', upload_to='post_images/'),
        ),
    ]
