# Generated by Django 2.2.3 on 2019-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190914_1414'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='askquestion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='aboutme',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
