# Generated by Django 2.2.3 on 2019-09-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190916_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='aboutme',
        ),
    ]
