# Generated by Django 2.2.3 on 2019-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
