# Generated by Django 2.2.3 on 2019-09-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190916_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutme',
        ),
    ]
