# Generated by Django 2.2.3 on 2019-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='aboutme',
            field=models.CharField(default='Let other know about yourself.', max_length=200),
        ),
    ]
