# Generated by Django 2.2.3 on 2019-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190916_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='aboutme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
