# Generated by Django 2.2.3 on 2019-09-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190916_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutme',
        ),
    ]
